This text editor is essentially just a SECD machine optimized for
representing buffers of text in a format that is useful for editing
operations and typesetting it to a display.

** Buffers

Everything is a buffer. That statement is not quite true, but it's
true enough. Files that we edit are loading into a buffer. When we
start a new file we start with an empty buffer and later bind it to
and save it to a file. Commands are typed into a (mini-) buffer.
Background status is stored in buffers. This is the magic that makes
Emacs so hackable.

A text file is a one-dimensional representation of a two-dimensional
document. For example, newlines are control characters that describe
how to convert the file into the 2d plane of glyphs.

This is an important point to remember. There's nothing sacred about
drawing one character at a time, from left to right, and when we get
to the right of the display wrapping to the next line by moving down
the glyph height and starting again at the far left and doing the
same when we reach a newline character instead of drawing it.

Painting a sequence of glyphs across the screen in a zig-zag is pretty
universal for text, but the direction you move isn't.

In fact, we will almost certainly want to visualize a sequence of
characters in different ways. For example: wrapping long lines vs
truncation.

And this brings up another difference, do we want the cursor to move
around the screen without any regard to the structure of the text
under it or does "move up" for example really mean move to the
previous line at the same column offset? And what happens if the
previous line is too short and doesn't have that column? And what
happens if you keep moving up and encounter another line that /is/
long enough? 

Mentally de-coupling the sequence of characters in a buffer with the
visualization opens up other potential improvements. Maybe we can also
display a PDF as either the textual format or as the drawn document
the author intended. Or we could constrain code files to always be
syntactically correct.

*** Buffer Representation

The choice of data structure for a buffer of text is dependent several
factors most notably how much text, whether it is full of many short
lines or few long lines, and whether it will be mostly just read or is
under active editing.

We recognized that we don't have to use the same data structure for
all active buffer nor even the same data structure for the buffer over
its lifetime.

**** Gap Buffers

In the actual implementation they use Gap Buffers. A buffer
initial starts off all gap, the first part is 0 length at
the beginning and the second part is 0 length at the end.

*** Create a new buffer

We will start here with the simplest command for the simplest buffer
implementation.

This is also where the buffer type is defined.

#+name: create_buffer
#+begin_src c
typedef struct Buffer {
  BufferId id;
  String name;
  u8* contents;
  u64 length;
  u64 point;
  // Mark mark; no need to this quite yet
  
} Buffer;

Buffer buffers[64];
u16 buffers_len;
BufferId current_buffer_id;

Status create_buffer(String name) {
  for (int i = 0; i < buffers_len; i++) {
    if (memcmp(buffers[i].name.s, name.s, name.len) == 0) {
      return Failure;
    }
  }
  int i = buffers_len++;
  Buffer * b = &buffers[i];
  b->id = i;
  b->name = name;
  b->contents = malloc(100);
  return Success;
}

Status set_current_buffer(String name) {
  for (int i = 0; i < buffers_len; i++) {
    if (memcmp(buffers[i].name.s, name.s, name.len) == 0) {
      current_buffer_id = i;
    }
  }
  return Failure;
}
#+end_src

*** Insert self

Insert the character that has been typed.

The universal argument is assumed to be the number of times to repeat
the character being inserted.

#+name: insert_self
#+begin_src c
Status insert_self(u21 ch) {
  u8 * b = buffers[current_buffer_id].contents;
  u64 loc = buffers[current_buffer_id].point;
  printf("Inserting %d to location %llu\n", ch, loc);
  u8 enc[4];
  u8 n = to_utf8(enc, ch);
  if (n == 0) return NotUnicode;
  memmove(b+loc+n, b+loc, n);
  memcpy(b+loc, enc, n);
  buffers[current_buffer_id].point++;
  buffers[current_buffer_id].length += n;
  return Success;
}
#+end_src

*** Unicode Helpers

#+name: unicode_helpers
#+begin_src c
typedef struct String { u8 len; u8 s[64]; } String;
String str(const char * x) {
  // TODO: assert string length
  String y = {.len=sizeof(x)};
  memcpy(y.s, x, y.len);
  return y;
}

u8 to_utf8(u8 * buf, u21 ch)
{
    if (ch <= 0x7F) {
        buf[0] = ch;
        return 1;
    }
    if (ch <= 0x7FF) {
        buf[0] = 0xC0 | (ch >> 6);            /* 110xxxxx */
        buf[1] = 0x80 | (ch & 0x3F);          /* 10xxxxxx */
        return 2;
    }
    if (ch <= 0xFFFF) {
        buf[0] = 0xE0 | (ch >> 12);           /* 1110xxxx */
        buf[1] = 0x80 | ((ch >> 6) & 0x3F);   /* 10xxxxxx */
        buf[2] = 0x80 | (ch & 0x3F);          /* 10xxxxxx */
        return 3;
    }
    if (ch <= 0x10FFFF) {
        buf[0] = 0xF0 | (ch >> 18);           /* 11110xxx */
        buf[1] = 0x80 | ((ch >> 12) & 0x3F);  /* 10xxxxxx */
        buf[2] = 0x80 | ((ch >> 6) & 0x3F);   /* 10xxxxxx */
        buf[3] = 0x80 | (ch & 0x3F);          /* 10xxxxxx */
        return 4;
    }
    return 0;
}
#+end_src

** Display

#+name: redisplay
#+begin_src c
Status redisplay(void) {
  printf("Buffer: %s\n", buffers[current_buffer_id].contents);
  return Success;
}
#+end_src


** Setup

#+name: typedefs
#+begin_src c :tangle build/third.c :noweb yes
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u21; // unicode code point, only use 21 bits
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef uint8_t Status;
typedef uint16_t BufferId;
//typedef char[8] Slug; // a short string (≤ 8 bytes)

enum {Success,Failure,NotUnicode};

<<unicode_helpers>>
<<create_buffer>>
<<insert_self>>
<<redisplay>>

int main(void) {
  create_buffer(str("*scratch*"));
  set_current_buffer(str("*scratch*"));
  insert_self('g');
  insert_self('u');
  insert_self('i');
  insert_self('d');
  insert_self('o');
  redisplay();
  return 0;
}

#+end_src

** Extensions

*** Lisp Nodes

The classic C implementation of a Lisp node is an implicit tagged
union of the native word size where the lower 3 bits of a pointer tag
the data that it points to and structs in the array-of-structs style.

The modern style is for a struct-of-arrays where we have large
contiguous swaths of identially typed data. We are going to assume a
64 bit native word size here for simplicity. I can think of no good
reason to make this program optimized for other word sizes. If it is
then the hypothetical 32-bit word size advocate is encouraged to fork
this codebase.

A block of 64 cells (4096 bytes) is a natural point of segmentation.
This allows flags for all 64 cells to each fit into a single 64 bit
word.

#+begin_src c
typedef struct Cons {
  u32 car;
  u32 cde;
} Cons;

typedef struct Cell {
  union {
    i64  n;
    u21  c; // unicode codepoint
    //Slug s;
    Cons p;
  } 
} Cell;

enum Tag {Number, Character, Slug, ConsPair};

Tag  tags[4096];
Cell cells[4096];
#+end_src




** Stupid Ideas

- Maybe a slug should store 7 bit ascii chars and use the remaining
  bits for length?
- When loading a file we can write out the text pretty quickly into a
  block of cells and then write out the car/cdr parts in a different
  part of the block all at once.

